### ISSUE TITLE
Throws error when hovering over elements with transparency

### ISSUE THREAD

**Issue by Ertan9** [frederfred/fontanello#14]
## Expected behavior
No errors.

## Actual behavior
Throws "Error: Parts is null" in browser console everytime I hover over a transparent element. The issue is solved when Fontanello is disabled.

## Steps to reproduce the problem
1) Create an element with transparency value less than 1 (Eg. below)
.demo {"background:rgba(0,0,0, 0.99);  width:100px; height:100px;"}
2) Hover over it
3) Browser console throws an error each time you hover.
Screenshot:
![fontanello](https://user-images.githubusercontent.com/33933125/116808259-7e4a7e80-ab40-11eb-9d26-6a4d70d732ba.png)

## Specifications

  - Version: 1.2.1
  - OS: Windows 10
  - Browser: Firefox 88.0

**Comment by frederfred** [comment]
Thanks for your bug report!

It looks like this issue came with the release of Firefox 88. I'll look into it and let you know when a fix is out.

**Comment by frederfred** [comment]
@Ertan9 this issue should be resolved in version 1.2.2 which is available for download. Please let me know if you experience any other issues!
